### ISSUE TITLE
Truncated output, leftover files in bam2wig.pl

### ISSUE THREAD

**Issue by balwierz** [tjparnell/biotoolbox#10]
I am running bam2wig.pl with the following options
--extend --rpm --nope --shift --shiftval -21 --extval 50 --cpu 8 --nogz --bw

It seems like the negative shift value causes problems around the beginning of the chromosomes.
The whole output looks like this:
``` This program will convert bam alignments to wig data
 Writing fixedStep format in 10 bp bins
 Alignments will be extended by 50 bp
 Forking into 8 children for parallel conversion
Modification of non-creatable array value attempted, subscript -2 at /usr/local/bin/bam2wig.pl line 2436.
Modification of non-creatable array value attempted, subscript -2 at /usr/local/bin/bam2wig.pl line 2436.
Modification of non-creatable array value attempted, subscript -1 at /usr/local/bin/bam2wig.pl line 2436.
Modification of non-creatable array value attempted, subscript -1 at /usr/local/bin/bam2wig.pl line 2436.
Modification of non-creatable array value attempted, subscript -2 at /usr/local/bin/bam2wig.pl line 2436.
Modification of non-creatable array value attempted, subscript -2 at /usr/local/bin/bam2wig.pl line 2436.
Modification of non-creatable array value attempted, subscript -1 at /usr/local/bin/bam2wig.pl line 2436.
Modification of non-creatable array value attempted, subscript -2 at /usr/local/bin/bam2wig.pl line 2436.
Modification of non-creatable array value attempted, subscript -2 at /usr/local/bin/bam2wig.pl line 2436.
Modification of non-creatable array value attempted, subscript -2 at /usr/local/bin/bam2wig.pl line 2436.
Modification of non-creatable array value attempted, subscript -2 at /usr/local/bin/bam2wig.pl line 2436.
Modification of non-creatable array value attempted, subscript -1 at /usr/local/bin/bam2wig.pl line 2436.
 Normalizing depth based on 237,495,068 total counted alignments
 Merging temporary files
 Writing directly to bigWig converter
 generating chromosome file....
 no filename provided or associated with object! at /usr/local/share/perl/5.26.1/Bio/ToolBox/utility.pm line 248.
Can't call method "close" on an undefined value at /usr/local/bin/bam2wig.pl line 2016.
```

And there are more problems:
- The resulting bigWig file contains signal only for chr1 and chr10. But the original BAM contains for all chromosomes. (There existed temporary files for other chromosomes during the execution time, but the values didn't end up in the bigWig output.)
- There are leftover files in the working directory: 12 files \*.f.temp.wig and one chr_sizes\* file

Bio::ToolBox version 1.54

**Comment by tjparnell** [comment]
Thanks for the note regarding the email. I hadn’t anticipated a negative shift, which will break things near the beginning of chromosomes. Since each fork writes it’s own separate file for every  chromosome, only those chromosomes without reads near the beginning “survived”, and the failed “dead” forks left behind truncated partial files. I think this should be easy to fix, though. I’ll take a look this weekend.

**Comment by balwierz** [comment]
Thanks.
Just to clarify what I am aiming at: I want to have a coverage of fixed width fragments (50pb) centred on transposase integration site. Therefore I need to shift the reads by negative value and extend it to the desired value. I am not shifting by half the width because of the way the protocol works, otherwise it would be -25.
So I think negative shifts are pretty desirable.
Cheers.

**Comment by balwierz** [comment]
I tested it again after your update and I can confirm that the update solves all the issues mentioned.
Thanks.

PS. I added --var to have varStep output, but the script refused to do that: "Writing variableStep wig files with bin size of 10 bp is not supported!". And I didn't specify bin size at all. Can I have a varStep output in extend mode?

**Comment by tjparnell** [comment]
Ah, you tested it before I had a chance to reply. Glad it’s working for you.

Yes, by default it resorts to a bin size of 10 bp for span, center-span, and extend modes. This results in a considerable savings in memory usage, file size, and performance without a significant loss in resolution when scanning at multiple kb or above. If you need base pair resolution, however, set the bin option to 1. The varStep wig output only supports a 1 bp bin (varStep gets too messy with multiple bp bin sizes). The start and midpoint modes are automatically set to a bin size of 1.
