### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by balwierz** [tjparnell/biotoolbox#13]
I had a bunch of bam2wig.pl running and some of them got I/O errors (probably a local problem).

Nevertheless bam2wig.pl finished in each case and produced files with missing chromosomes!
I wish it rather failed and produced no output, than produced a truncated output which is hard to spot.

Errors could be due to my config. They look like this:
```
cannot write to file 'bam2wigTEMP_1evN/myfile.chr22.2118834.f.temp.bin' Input/output error
```

**Comment by tjparnell** [comment]
Interesting. What are the options you're using?

The Input/output error is definitely a local problem (disk full, disk unavailable, permission, something). However, there is already code that checks for each chromosome wig file (not the temporary binary bin file, but the wig file after normalization) when writing to the final (big)wig file. If a chromosome wig file is missing, it should bail and attempt to clean up the temporary directory with temp files. For example, when I manually delete temporary chromosome bin or wig files (mimicking a failed sub-process), I get this

` Merging temporary files
 28,162,627 total alignments
 Writing directly to bigWig converter
 generating chromosome file....
 no filename provided or associated with object! at /Users/tim/perl5/perlbrew/perls/perl-5.28/lib/site_perl/5.28.1/Bio/ToolBox/utility.pm line 248.
one or more sub-process forks failed! Check your parameters and input file.
Attempting to clean up
`
Even when I have multiple input bam files, manually deleting a temp file prematurely will cause it to crash someplace else. 

I can insert another check to make sure the number of temporary files equals what I expect. That might help, so it will simply bail earlier.

**Comment by balwierz** [comment]
My options are
` --pos span --pe --rpm --maxsize 500 --fix --in in.bam --cpu 8 --nogz --out $b.wig `.

I did not delete a file. More likely these are some nfs issues or file system getting full. This looks to me (but I might be wrong) as some exception from C code (there is no module and line information).

**Comment by tjparnell** [comment]
Yes, it's a low-level issue writing. Unfortunately, with that the case, it's hard to replicate to test. Deleting a temp file was just my lame attempt at mimicking a sub-process that failed. Without a reproducible test condition, this is going to be hard to fix. Like I said, I can insert another check to see if all the temp files made it, but not confident that'll fix your problem.
