### ISSUE TITLE
Issue on installing Biotoolbox

### ISSUE THREAD

**Issue by marissa97** [tjparnell/biotoolbox#16]
Hello, 

I am trying to download Bio::ToolBox
It looks like it is now downloaded, however when i run: `perl ucsc_table2gff3.pl -f refgene -d hg19`
it delivers an error: 
```
Can't locate Bio/ToolBox.pm in @INC (you may need to install the Bio::ToolBox module) (@INC contains: /home/marissa/miniconda3/lib/perl5/5.32/site_perl /home/marissa/miniconda3/lib/perl5/site_perl /home/marissa/miniconda3/lib/perl5/5.32/vendor_perl /home/marissa/miniconda3/lib/perl5/vendor_perl /home/marissa/miniconda3/lib/perl5/5.32/core_perl /home/marissa/miniconda3/lib/perl5/core_perl .) at ucsc_table2gff3.pl line 9.
BEGIN failed--compilation aborted at ucsc_table2gff3.pl line 9.
```
Can you please tell me what is wrong ?
Thank you!

**Comment by tjparnell** [comment]
Hello,
Based on your error, the package is not installed properly. Did you run the `Build` script, or go through a Perl package manager such as `cpan`, `cpanm`, or `cpanp`? For more details look at the [Advanced Install](https://github.com/tjparnell/biotoolbox/blob/master/docs/AdvancedInstallation.md) documentation.

As of this writing, the current version here on GitHub is considerably different (and mostly incompatible) with the released versions on CPAN, but is stable.

The `ucsc_table2gff3.pl` script is pretty old and I've had to strip out modern incompatibilities. You can also use the `get_features.pl` script, with the appropriate flags, if you're looking to simply convert annotation formats.
